theme: jekyll-theme-cayman

# To resolve urls properly
baseurl: "/snake-game" # the subpath of your site, e.g. /blog
url: "https://kmurphs.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Site Presentation
title: Snake Game
description: Simple Snake Game implemented using React.

# Use for linking portfolio landing page to project
skills: React, Javascript/Typescript, Redux, React Router, Game, Functional Programming, State Management, TailwindCSS, Local Storage
banner: https://raw.githubusercontent.com/KMurphs/snake-game/gh-pages/assets/imgs/hero.png